services:
  nginx:
    build: ./nginx/
    ports:
      - 8080:8080

    volumes:
      - ./src/:/var/www/html/

  php:
    build: .
    expose:
      - 9000
    develop:
      watch:
        - action: sync
          path: ./src/
          target: /var/www/html/
        - action: rebuild
          path: composer.json
          target: /var/www/html/
        - action: rebuild
          path: composer.lock
          target: /var/www/html/
